image: python:3.9-slim

stages:
    - test
    - deploy

include:
    - template: Security/SAST.gitlab-ci.yml

autounit:
    stage: test
    script:
        - python -m unittest

scrapinghub:
    stage: deploy
    script:
        - apt-get update
        - apt-get install gcc rpl -y
        - pip install -r requirements.txt
        - rpl '$SHUB_API_KEY' $SHUB_API_KEY scrapinghub.yml
        - shub deploy
    only:
        - master
    environment:
        name: scrapinghub
        url: $ENV_URL
